/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test
 * Method:    maincall
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test_maincall
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
